"type" = "fg"
"constant" = "fg"
"constant.numeric" = "fg"
"constant.character.escape" = "fg"
"string" = "lgray"
"string.regexp" = "lgray"
"comment" = "gray"
"variable" = "fg"
"variable.builtin" = "fg"
"variable.parameter" = "fg"
"variable.other.member" = "fg"
"label" = "gray"
"punctuation" = "gray"
"punctuation.delimiter" = "gray"
"punctuation.bracket" = "gray"
"keyword" = { fg = "fg", modifiers = ["bold"] }
"keyword.directive" = { fg = "fg", modifiers = ["bold"] }
"operator" = { fg = "fg", modifiers = ["bold"] }
"function" = "fg"
"function.builtin" = "fg"
"function.macro" = "fg"
"tag" = "gray"
"namespace" = "fg"
"attribute" = "fg"
"constructor" = "fg"
"module" = "fg"
"special" = "fg"

"markup.heading.marker" = "gray"
"markup.heading.1" = { fg = "fg", modifiers = ["bold"] }
"markup.heading.2" = { fg = "fg", modifiers = ["bold"] }
"markup.heading.3" = { fg = "fg", modifiers = ["bold"] }
"markup.heading.4" = { fg = "fg", modifiers = ["bold"] }
"markup.heading.5" = { fg = "fg", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg", modifiers = ["bold"] }
"markup.list" = "fg"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "purple"
"markup.quote" = "gray"
"markup.raw" = "fg"

"diff.plus" = "green"
"diff.delta" = "orange"
"diff.minus" = "red"

"ui.background" = { bg = "bg" }
"ui.background.separator" = "gray"
"ui.cursor" = { fg = "white", bg = "black" }
"ui.cursor.match" = { fg = "fg", bg = "gray" }
"ui.cursor.insert" = { fg = "white", bg = "black" }
"ui.cursor.select" = { fg = "white", bg = "black" }
"ui.cursorline.primary" = { bg = "black", fg = "white" }
"ui.cursorline.secondary" = { bg = "bg" }
"ui.selection" = { fg = "white", bg = "black" }
"ui.linenr" = "gray"
"ui.linenr.selected" = { fg = "fg", modifiers = ["bold"] }
"ui.statusline" = { fg = "fg", bg = "bg" }
"ui.statusline.inactive" = { fg = "gray", bg = "bg" }
"ui.statusline.normal" = { fg = "bg", bg = "fg", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg", bg = "yellow", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg", bg = "blue", modifiers = ["bold"] }
"ui.bufferline" = { fg = "gray", bg = "bg" }
"ui.bufferline.active" = { fg = "fg", bg = "bg", modifiers = ["bold"] }
"ui.popup" = { fg = "gray", bg = "popup" }
"ui.window" = { fg = "gray", bg = "bg" }
"ui.help" = { fg = "fg", bg = "bg" }
"ui.text" = "fg"
"ui.text.focus" = { fg = "fg", bg = "bg" }
"ui.menu" = { fg = "fg", bg = "bg" }
"ui.menu.selected" = { fg = "fg", bg = "gray" }
"ui.menu.scroll" = {fg = "fg"}
"ui.virtual.whitespace" = { fg = "bg" }
"ui.virtual.indent-guide" = { fg = "bg" }
"ui.virtual.ruler" = { bg = "bg" }
"ui.virtual.inlay-hint" = "hints"
"ui.highlight" = {fg = "red", bg = "popup"}
"ui.highlight.frameline" = {fg = "white", bg = "black"}

"hint" = "blue"
"info" = "green"
"warning" = "yellow"
"error" = "red"
"diagnostic" = { underlined = { style = "line" } }
"diagnostic.hint" = { underline = { color = "blue", style = "dotted" } }
"diagnostic.info" = { underline = { color = "green", style = "dotted" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]
fg = "#000000"
bg = "#FFFFFF"
lgray = "#575757"
gray = "#7D7D7D"
hints = "#B4B4B4"
popup = "#F6F6F6"